### ISSUE TITLE
Unauthenticated user scores not saved

### ISSUE THREAD

**Issue by MrMoneyInTheBank** [MrMoneyInTheBank/zetamax#13]
Scores for unauthenticated users is not saved for analytics. Currently, the convex database only holds scores for active users who have logged in via clerk. 

Steps to resolve

- Store unauthenticated user score in local storage within browser
- When a new user is created, check within local storage if there are cached scores
- migrate scores to convex database

**Comment by joeberetta** [comment]
One more bug w/ this case I found

> Originally posted here: https://www.reddit.com/r/opensource/s/DLBa5xme7A

Shortly, bug is reproducible as I found only for unauthed "session" after first game over

Here's the screenshot of result instead of many words...
![image](https://github.com/user-attachments/assets/4c729201-4dac-4e8f-8f68-859ac8e5c09f)

**Comment by MrMoneyInTheBank** [comment]
I am assuming you are not talking about the ui issues (will address responsive design in another issue). Just so I understand correctly, is the bug that analytics graph is not being updated after game for anonymous user? If so, commit 1710e82,  05a471b, and 634c864 address this. Please let me know if I misunderstood @joeberetta

**Comment by joeberetta** [comment]
> I am assuming you are not talking about the ui issues (will address responsive design in another issue). Just so I understand correctly, is the bug that analytics graph is not being updated after game for anonymous user? If so, commit 1710e82,  05a471b, and 634c864 address this. Please let me know if I misunderstood @joeberetta 

I didn't catch problem w/ graph updating

I meant that after I ended the game I got NaN/Infinity values instead of correct ones
